# Generated by Django 4.1.2 on 2022-10-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="province",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
