# Generated by Django 4.1.2 on 2022-10-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
