# Generated by Django 4.1.2 on 2022-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0003_data_migrations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name="farm",
            name="product",
        ),
        migrations.AddField(
            model_name="farm",
            name="products",
            field=models.ManyToManyField(to="farming.product"),
        ),
    ]
