# Generated by Django 4.1.2 on 2022-10-13 18:18
# Guide followed: https://dev.to/koladev/writing-custom-migrations-in-django-3eli

from django.db import migrations

FARM_PRODUCTS = ["Dairy", "Poultry", "Flower", "Organic", "Fish", "Bee yard", "Hay"]

def create_products(apps, schema_editor):
    Product = apps.get_model('farming', 'Product')

    for product in FARM_PRODUCTS:
        Product.objects.create(
            name=product,
        )

class Migration(migrations.Migration):

    dependencies = [
        ("farming", "0004_product_remove_farm_product_farm_products"),
    ]

    operations = [
        migrations.RunPython(create_products)
    ]
